package com.docuai.common.exception;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_REVOKED,
    AUTH_INSUFFICIENT_PERMISSIONS,
    VALIDATION_ERROR,
    DOCUMENT_TYPE_NOT_FOUND,
    DOCUMENT_TYPE_REFERENCED,
    EXTRACTION_JOB_NOT_FOUND,
    EXTRACTION_FAILED,
    CONVERSATION_NOT_FOUND,
    MESSAGE_NOT_FOUND,
    GENERATED_DOCUMENT_NOT_FOUND,
    EXPORT_FAILED,
    AI_PROVIDER_UNAVAILABLE,
    AI_PROVIDER_ERROR,
    AI_CONFIG_NOT_FOUND,
    AI_CONFIG_IS_DEFAULT,
    USER_NOT_FOUND,
    USER_EMAIL_DUPLICATE,
    CATEGORY_NOT_FOUND,
    CATEGORY_REFERENCED,
    FILE_TOO_LARGE,
    FILE_TYPE_NOT_SUPPORTED,
    STORAGE_ERROR,
    INTERNAL_ERROR
}
