spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

extraction:
  use-mock: true

logging:
  level:
    com.docuai: DEBUG
    org.hibernate.SQL: DEBUG

spring.ai:
  mistralai:
    api-key: "dummy-key-for-dev"
